---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(stringr)
library(lubridate)
library(ggplot2)
```

# Businness in SF

```{r}
#data <- read.csv("~/business_sf.csv")
data <- read.csv("~/Desktop/crime_in_sf/crime_in_sf/business_sf.csv")
```

```{r}
colnames(data)
summary(data$City)
```

```{r}
bus_sf = data[which(data$City == "San Francisco"), ]
```



```{r}
summary(bus_sf)
sum(is.na(bus_sf$Business.Location))
head(bus_sf$Business.Location)
```


```{r}
x = str_split_fixed(bus_sf$Business.Location, pattern =  "[()]",  n = 3)
xy = x[,2]
coordinates = str_split_fixed(xy, pattern =  ",",  n = 2)
```

```{r}
coordinates = as.data.frame(coordinates)
colnames(coordinates) = c("Y", "X")
```



```{r}
bus_sf = cbind(bus_sf, coordinates)
```

```{r}
glimpse(bus_sf)
```



```{r}
colnames(bus_sf)

bus_sf = bus_sf[, c(18, 27, 28)]
```



```{r}
write.csv(bus_sf, file = "bus_sf.csv")
```



## Air traffic
```{r message=FALSE, warning=FALSE}
air_traffic_sf <- read_csv("air_traffic_sf.csv")
```

```{r}
colnames(air_traffic_sf)
glimpse(air_traffic_sf)
```




```{r}
data = air_traffic_sf
data$`Activity Period` = parse_date_time(data$`Activity Period`, orders = "Ym")


```


```{r}
colnames(data)
head(data)
glimpse(data)
summary(data)
unique(data$`Activity Period`)
data = data[, c(1, 6, 7, 8, 9, 12)]

colnames(data) <- c("Date", 
                    "geo", "geo_region", 
                    "activity", "price", 
                    "passengers")
```

```{r}
data$year = year(data$Date)
data$month = month(data$Date)


```


```{r}


landings_2005 = data[data$Date >= "2005-01-01" & data$Date  <= "2005-12-31", ]
landings_2006 = data[data$Date >= "2006-01-01" & data$Date  <= "2006-12-31", ]
landings_2007 = data[data$Date >= "2007-01-01" & data$Date  <= "2007-12-31", ]

landings_2008 = data[data$Date >= "2008-01-01" & data$Date  <= "2008-12-31", ]

landings_2009 = data[data$Date >= "2009-01-01" & data$Date  <= "2009-12-31", ]

landings_2010 = data[data$Date >= "2010-01-01" & data$Date  <= "2010-12-31", ]

landings_2011 = data[data$Date >= "2011-01-01" & data$Date  <= "2011-12-31", ]
landings_2012 = data[data$Date >= "2012-01-01" & data$Date  <= "2012-12-31", ]
landings_2013 = data[data$Date >= "2013-01-01" & data$Date  <= "2013-12-31", ]
landings_2014 = data[data$Date >= "2014-01-01" & data$Date  <= "2014-12-31", ]
landings_2015 = data[data$Date >= "2015-01-01" & data$Date  <= "2015-12-31", ]
landings_2016 = data[data$Date >= "2016-01-01" & data$Date  <= "2016-12-31", ]
landings_2017 = data[data$Date >= "2017-01-01" & data$Date  <= "2017-12-31", ]

```


```{r}
test <- aggregate(passengers ~ month, landings_2017, FUN = sum)
head(test)
```

```{r}
d = aggregate(passengers ~ month + year, data, FUN = sum)
```

```{r}
head(d)
glimpse(d)
d$month = as.factor(d$month)
d$year = as.factor(d$year)
```


```{r}
d = data
d = d[which(d$year < 2018),]

summary(d)
glimpse(d)
dd$month = as.factor(dd$month)
dd$year = as.factor(dd$year)



dd = aggregate(passengers ~ month + year, data, FUN = sum)

```


```{r}
ggplot(data=dat1, aes(x=time, y=total_bill, group=sex, shape=sex, colour=sex)) + 
    geom_line(aes(linetype=sex), size=1) +     # Set linetype by sex
    geom_point(size=3, fill="white") +         # Use larger points, fill with white
    expand_limits(y=0) +                       # Set y range to include 0
    scale_colour_hue(name="Sex of payer",      # Set legend title
                     l=30)  +                  # Use darker colors (lightness=30)
    scale_shape_manual(name="Sex of payer",
                       values=c(22,21)) +      # Use points with a fill color
    scale_linetype_discrete(name="Sex of payer") +
    xlab("Time of day") + ylab("Total bill") + # Set axis labels
    ggtitle("Average bill for 2 people") +     # Set title
    theme_bw() +
    theme(legend.position=c(.7, .4))           # Position legend inside
                                               # This must go after theme_bw
```

```{r}
glimpse(dd)
```

```{r}
dd$month[dd$month == 1] <- "Jan"
dd$month[dd$month == 2] <- "Feb"
dd$month[dd$month == 3] <- "March"
dd$month[dd$month == 4] <- "April" 
dd$month[dd$month == 5] <- "May"
dd$month[dd$month == 6] <- "June"
dd$month[dd$month == 7] <- "July"
dd$month[dd$month == 8] <- "Aug"
dd$month[dd$month == 9] <- "Sep"
dd$month[dd$month == 10] <- "Oct"
dd$month[dd$month == 11] <- "Nov"
dd$month[dd$month == 12] <- "Dec"
```

```{r}
table(cat7$knows_status, useNA = "ifany")
cat7$knows_status[cat7$knows_status == 9] <- NA
cat7$knows_status[cat7$knows_status == 8] <- 0
cat7$knows_status[cat7$knows_status == 2] <- 0
table(cat7$knows_status, useNA = "ifany")
```


```{r}
fancy_scientific <- function(l) {
     # turn in to character string in scientific notation
     l <- format(l, scientific = TRUE)
     # quote the part before the exponent to keep all the digits
     l <- gsub("^(.*)e", "'\\1'e", l)
     # turn the 'e+' into plotmath format
     l <- gsub("e", "%*%10^", l)
     # return this as an expression
     parse(text=l)
}
```


```{r}

png(file ="passengers_sf.png",width = 600,height = 350, res = 75)

ggplot(data = dd, aes(x = month, y = passengers, group = year, colour = year)) +
  geom_line(aes(linetype = year), size = 1) +
  geom_point(size = .5, fill = "white") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.title.x = element_blank()) + 
  theme(axis.text.x = element_text(face = "bold", size = 10),
        axis.text.y = element_text(face = "bold", size = 10)) +
  scale_y_continuous(labels = fancy_scientific) +
  scale_x_discrete(labels = c("1" = "Jan", 
                            "2" = "Feb",
                            "3" = "March",
                            "4" = "April",
                            "5" = "May",
                            "6" = "June",
                            "7" = "July",
                            "8" = "Aug",
                            "9" = "Sep",
                            "10" = "Oct",
                            "11" = "Nov",
                            "12" = "Dec"
                            ))

dev.off()
```



## Food in SF



```{r}
#food_sf <- read.csv("~/Desktop/crime_in_sf/food_sf.csv")
```

```{r}
#summary(food_sf$Status)
```


```{r}

#food = food_sf[ , c(3,15:16)]

#head(food)

```

```{r}
#write.csv(food, file = "food.csv")
```
